language: go
go:
  - "1.9.x"
dist: trusty
sudo: required
group: edge
env:
  - CHANGE_MINIKUBE_NONE_USER=true

jobs:
  include:
    - stage: "build"
      script:
        - ./scripts/travis.sh format
    -
      script:
        - ./scripts/travis.sh vet
    -
      script:
        - ./scripts/travis.sh lint
    -
      script:
        - ./scripts/travis.sh build
    -
      script:
        - ./scripts/travis.sh test
    - stage: "integration"
      before_install:
        - ./scripts/travis.sh docs; if [ $? -eq 9 ]; then exit 0; fi
        - ./scripts/travis.sh before_install
      install:
        - ./scripts/travis.sh install
      before_script:
        - ./scripts/travis.sh before_script
        - ./scripts/travis.sh setup-cluster
        - ./scripts/travis.sh setup-broker
      script:
        - ./scripts/travis.sh ci
        - ./scripts/broker-ci/gather-logs.sh
    -
      before_install:
        - ./scripts/travis.sh docs; if [ $? -eq 9 ]; then exit 0; fi
      before_script:
        - ./scripts/travis.sh setup-minikube
        - ./scripts/travis.sh k8s-catalog
        - ./scripts/travis.sh pv-setup
        - ./scripts/travis.sh k8s-broker
      script:
        - ./scripts/travis.sh k8s-ci
        - ./scripts/broker-ci/gather-logs.sh
