language: go
go:
  - "1.9.x"
dist: trusty
sudo: required
group: edge
env:
  - CHANGE_MINIKUBE_NONE_USER=true

jobs:
  include:
    - stage: "OpenShift and Kubernetes CI"
      before_install:
        - ./scripts/travis.sh docs; if [ $? -eq 9 ]; then exit 0; fi
        - ./scripts/travis.sh before_install
      install:
        - ./scripts/travis.sh install
      before_script:
        - ./scripts/travis.sh before_script
        - ./scripts/travis.sh format
        - ./scripts/travis.sh vet
        - ./scripts/travis.sh lint
        - ./scripts/travis.sh build
        - ./scripts/travis.sh test
        - ./scripts/travis.sh setup-cluster
        - ./scripts/travis.sh setup-broker
      script:
        - ./scripts/travis.sh ci
        - ./scripts/broker-ci/gather-logs.sh
    -
      before_install:
        - ./scripts/travis.sh docs; if [ $? -eq 9 ]; then exit 0; fi
      before_script:
        - ./scripts/travis.sh setup-minikube
        - ./scripts/travis.sh k8s-catalog
        - ./scripts/travis.sh pv-setup
        - ./scripts/travis.sh k8s-broker
      script:
        - ./scripts/travis.sh k8s-ci
        - ./scripts/broker-ci/gather-logs.sh
