apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: asb-operator
  namespace: openshift-operator-lifecycle-manager
spec:
  configMap: asb-operator
  displayName: Automation Broker
  publisher: Red Hat
  sourceType: internal
