---
registry:
  name: dev
  url: http://localhost:1337
  user: xxx
  pass: xxx
dao:
  etcd_host: localhost
  etcd_port: 2379
log:
  logfile: /tmp/ansible-service-broker.log
  stdout: true
  level: debug
  color: true
