---
registry:
  - type: dockerhub
    name: docker
    url: https://registry.hub.docker.com
    org: DOCKERHUB_ORG
    fail_on_error: false
  - type: rhcc
    name: rhcc
    url: registry.access.stage.redhat.com
    fail_on_error: true
    white_list:
      - "^legitimate.*-apb$"
      # will allow all the APBs to be included. You must have at least 1 white
      # list to retrieve APBs and this is the most permissive
      - ".*-apb$"
    black_list:
      - "malicious.*-apb$"
      - "^specific-blacklist-apb$"
dao:
  etcd_host: localhost
  etcd_port: 2379
log:
  logfile: /var/log/ansible-service-broker/asb.log
  stdout: true
  level: debug
  color: true
openshift:
  host: ""
  ca_file: ""
  bearer_token_file: ""
  image_pull_policy: IfNotPresent
  sandbox_role: "edit"
  keep_namespace: false
  keep_namespace_on_error: true
broker:
  bootstrap_on_startup: true
  dev_broker: true
  launch_apb_on_bind: false
  recovery: true
  output_request: true
  ssl_cert_key: /path/to/key
  ssl_cert: /path/to/cert
  refresh_interval: "600s"
  auth:
    - type: basic
      enabled: true
