---
registry:
  name: dockerhub
  url: http://localhost:1337
  user: DOCKERHUB_USER
  pass: DOCKERHUB_PASS
  org: DOCKERHUB_ORG
dao:
  etcd_host: localhost
  etcd_port: 2379
log:
  logfile: /var/log/ansible-service-broker/asb.log
  stdout: true
  level: debug
  color: true
openshift:
  host: ""
  ca_file: ""
  bearer_token_file: ""
  image_pull_policy: IfNotPresent
broker:
  dev_broker: true
  launch_apb_on_bind: false
  recovery: true
  output_request: true
  whitelist: "/etc/ansible-service-broker/whitelist.yaml"
  blacklist: "/etc/ansible-service-broker/blacklist.yaml"
