---

broker_name: ansible-service-broker
broker_namespace: openshift-ansible-service-broker

# 3.11 compatible names
broker_deployment_name: asb
broker_service_name: asb
broker_route_name: asb-1338
dashboard_redirector_route_name: dr-1337

broker_image: docker.io/ansibleplaybookbundle/origin-ansible-service-broker:v3.11

broker_kind: ClusterServiceBroker
broker_image_pull_policy: "IfNotPresent"
broker_probe_initial_delay: 120
broker_node_selector: ""
broker_basic_auth_enabled: false

_broker_config:
  registry:
    - type: dockerhub
      name: dh
      url: https://registry.hub.docker.com
      org: ansibleplaybookbundle
      tag: latest
      white_list:
        - ".*-apb$"
      black_list:
        - ".*automation-broker-apb$"
  dao:
    type: crd
  log:
    logfile: /var/log/ansible-service-broker/asb.log
    stdout: true
    level: debug
    color: true
  openshift:
    host: ''
    ca_file: ''
    bearer_token_file: ''
    image_pull_policy: "IfNotPresent"
    sandbox_role: "edit"
    namespace: "{{ broker_namespace | quote }}"
    keep_namespace: "false"
    keep_namespace_on_error: "false"
  broker:
    dev_broker: "true"
    bootstrap_on_startup: "true"
    refresh_interval: "600s"
    launch_apb_on_bind: "false"
    output_request: "true"
    recovery: "true"
    ssl_cert_key: /etc/tls/private/tls.key
    ssl_cert: /etc/tls/private/tls.crt
    auto_escalate: "false"
  auth:
    - type: basic
      enabled: false
