apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: asb
  namespace: ansible-service-broker
  labels:
    app: ansible-service-broker
    service: asb
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: ansible-service-broker
        service: asb
    spec:
      restartPolicy: Always
      containers:
        - image: "{{dockerhub_org}}/ansible-service-broker-asb:latest"
          name: asb
          imagePullPolicy: Always
          ports:
            - containerPort: 1338
              protocol: TCP
          env:
            - name: DOCKERHUB_PASS
              value: "{{dockerhub_pass}}"
            - name: DOCKERHUB_USER
              value: "{{dockerhub_user}}"
            - name: DOCKERHUB_ORG
              value: "{{dockerhub_org}}"
            - name: OPENSHIFT_PASS
              value: "{{openshift_pass}}"
            - name: OPENSHIFT_TARGET
              value: "{{openshift_target}}"
            - name: OPENSHIFT_USER
              value: "{{openshift_user}}"
