---

{% if cluster == 'kubernetes' %}
apiVersion: apps/v1
kind: Deployment
{% else %}
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
{% endif %}
metadata:
  name: {{ broker_name }}
  namespace: {{ broker_namespace }}
  labels:
    app: {{ broker_name }}
    service: {{ broker_name }}
spec:
  replicas: 1
{% if cluster == 'kubernetes' %}
  selector:
    matchLabels:
      app: {{ broker_name }}
      service: {{ broker_name }}
  strategy:
    type: RollingUpdate
{% else %}
  selector:
    app: {{ broker_name }}
    service: {{ broker_name }}
  strategy:
    type: Rolling
{% endif %}
{% if broker_node_selector != "" %}
  nodeSelector: '{{ broker_node_selector }}'
{% endif %}
  template:
    metadata:
      labels:
        app: {{ broker_name }}
        service: {{ broker_name }}
    spec:
      serviceAccount: {{ broker_name }}
      containers:
        - name: broker-redirector
          image: {{ broker_image }}
          imagePullPolicy: {{ broker_image_pull_policy }}
          ports:
            - containerPort: 1337
              protocol: TCP
          command: [ 'dashboard-redirector' ]
        - name: broker
          image: {{ broker_image }}
          imagePullPolicy: {{ broker_image_pull_policy }}
          ports:
            - containerPort: 1338
              protocol: TCP
          env:
            - name: BROKER_CONFIG
              value: /etc/{{ broker_name }}/config.yaml
          resources: {}
          terminationMessagePath: /tmp/termination-log
          readinessProbe:
            httpGet:
              path: /healthz
              port: 1338
              scheme: HTTPS
            initialDelaySeconds: {{ broker_probe_initial_delay }}
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              port: 1338
              path: /healthz
              scheme: HTTPS
            initialDelaySeconds: {{ broker_probe_initial_delay }}
            timeoutSeconds: 1
          volumeMounts:
            - name: config-volume
              mountPath: /etc/{{ broker_name }}
            - name: broker-tls
              mountPath: /etc/tls/private
{% if broker_basic_auth_enabled | bool %}
            - name: broker-auth-volume
              mountPath: /var/run/asb-auth
{% endif %}
{% if broker_dao_type == 'etcd' %}
            - name: etcd-auth
              mountPath: /var/run/etcd-auth
{%   if cluster == 'kubernetes' %}
            - name: etcd-ca
              mountPath: /var/run/etcd-ca
{%   endif %}
{% endif %}
      volumes:
        - name: config-volume
          configMap:
            name: broker-config
            items:
            - key: broker-config
              path: config.yaml
        - name: broker-tls
          secret:
            secretName: {{ broker_tls_name }}
{% if broker_basic_auth_enabled | bool %}
        - name: broker-auth-volume
          secret:
            secretName: broker-auth
{% endif %}
{% if broker_dao_type == 'etcd' %}
        - name: etcd-auth
          secret:
            secretName: etcd-auth
{%   if cluster == 'kubernetes' %}
        - name: etcd-ca
          secret:
            secretName: etcd-ca
{%   endif %}
{% endif %}
